name: Run tests

on:
  push:
    branches: [config/ci]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysqlversion: ["5.7", "8.0"]
    services:
      mysql:
        image: mysql:${{ matrix.mysqlversion }}
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Prepare environment
      run: |
        sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

    - name: Run Tests
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
      run: |
        pytest app/modules/ --ignore-glob='*selenium*'

  outdated_dependencies:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v4
      with:
      python-version: 3.10.12
    - name: Install Codacy Coverage Reporter
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
